name: Publish to GitHub Packages

on:
  push:
      branches:
          - main

jobs:
  publish:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Pack
        run: dotnet pack --no-build --configuration Release --output out

      - name: Publish
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          source-url: https://nuget.pkg.github.com/proranked/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish NuGet Package
        run: dotnet nuget push out/*.nupkg --skip-duplicate
